import { generateAiReply } from "./aiService";
import { robustJsonParse } from "../shared/json";
import type { ActionType } from "../types";
import type { PageSnapshot } from "../shared/types/messages";

export interface ReasoningDecision {
  reasoning: string;
  selectedTool: ActionType;
  confidence: number;
  status: "continue" | "retry" | "replan" | "complete";
}

export const ReasoningEngine = {
  /**
   * Evaluates the context and reasons over the next cognitive step.
   * Returns a structured decision object.
   */
  async reason(contextString: string, pageContext?: PageSnapshot): Promise<ReasoningDecision> {
    // 1. Calculate DOM parser confidence score
    let domConfidence = 0.85;
    if (!pageContext || !pageContext.content || pageContext.content.trim().length < 300) {
      domConfidence = 0.42; // Low confidence flag
    }

    // 2. Inject warnings if DOM confidence is too low
    let lowDomWarningNotice = "";
    if (domConfidence < 0.50) {
      lowDomWarningNotice = `\n[WARNING: LOW DOM CONFIDENCE (${domConfidence})] The standard DOM parser could not locate sufficient structured text or fields on this page (likely canvas-based, rich visual, or heavily obfuscated). You MUST select visual tools such as "vision_click", "vision_fill", or "vision_analyze" to capture screenshots and interact by visual coordinates instead of DOM elements.`;
    }

    const prompt = `You are the core Cognitive Reasoning Brain for HUNTERR, an autonomous job search browser assistant.
Your task is to analyze the current goal, active webpage, user profile, and execution history, and determine the next best action.
${lowDomWarningNotice}

${contextString}

Instructions:
1. Examine the goal and what has been done so far.
2. Determine if the goal is fully accomplished, requires a tool, or is blocked.
3. Select the most appropriate tool from "Available Tools" to move closer to the goal.
4. Output your decision as a clean, valid JSON block. Do not include markdown code fences, comments, or explanations, just the raw JSON:

{
  "reasoning": "Explain step-by-step why you selected this action and how it relates to the goal.",
  "selectedTool": "Name of the tool (must match one of the available tool names exactly, e.g., 'extract_job', 'match_resume', 'fill_form', 'vision_click', 'vision_fill', 'chat_fallback')",
  "confidence": 0.85 (your confidence score in this selection, between 0.0 and 1.0),
  "status": "continue" (use "continue" to run the tool, "retry" to run the last action again, "replan" to change strategy, or "complete" if the goal is achieved or fully blocked)
}`;

    const responseText = await generateAiReply({
      prompt,
      history: [],
      pageContext
    });

    try {
      const parsed = robustJsonParse<Partial<ReasoningDecision>>(responseText);
      
      const reasoning = parsed.reasoning || "Reasoning trace not generated by LLM.";
      let selectedTool = (parsed.selectedTool || "chat_fallback") as ActionType;
      const confidence = typeof parsed.confidence === "number" ? parsed.confidence : 0.5;
      
      // Auto-fallback mapping on low DOM confidence
      if (domConfidence < 0.50) {
        if (selectedTool === "click_element") {
          selectedTool = "vision_click";
        } else if (selectedTool === "fill_input") {
          selectedTool = "vision_fill";
        } else if (selectedTool === "fill_form") {
          selectedTool = "vision_fill"; // Map visual forms to sequential inputs
        }
      }

      // Ensure status is valid
      let status: ReasoningDecision["status"] = "continue";
      if (parsed.status === "retry" || parsed.status === "replan" || parsed.status === "complete") {
        status = parsed.status;
      }

      return {
        reasoning,
        selectedTool,
        confidence,
        status
      };
    } catch (error) {
      console.error("Failed to parse reasoning decision JSON. Raw response:", responseText, error);
      return {
        reasoning: "Failed to parse structured reasoning decision, falling back to chat.",
        selectedTool: domConfidence < 0.50 ? "vision_analyze" : "chat_fallback",
        confidence: 0.2,
        status: "complete"
      };
    }
  }
};
