import { generateAiReply } from "./aiService";
import { robustJsonParse } from "../shared/json";
import type { ActionType } from "../types";
import type { PageSnapshot } from "../shared/types/messages";
import { PromptManager } from "./core/PromptManager";
import { evaluateDomConfidence, DOM_CONFIDENCE_THRESHOLD } from "./domConfidence";

export interface ReasoningDecision {
  reasoning: string;
  selectedTool: ActionType;
  confidence: number;
  status: "continue" | "retry" | "replan" | "complete";
}

export const ReasoningEngine = {
  /**
   * Evaluates the context and reasons over the next cognitive step.
   * Returns a structured decision object.
   */
  async reason(contextString: string, pageContext?: PageSnapshot): Promise<ReasoningDecision> {
    // 1. Calculate DOM parser confidence score
    const domConfidence = evaluateDomConfidence(pageContext);

    // 2. Inject warnings if DOM confidence is too low
    let lowDomWarningNotice = "";
    if (domConfidence < DOM_CONFIDENCE_THRESHOLD) {
      lowDomWarningNotice = `\n[WARNING: LOW DOM CONFIDENCE (${domConfidence})] The standard DOM parser could not locate sufficient structured text or fields on this page (likely canvas-based, rich visual, or heavily obfuscated). You MUST select visual tools such as "vision_click", "vision_fill", or "vision_analyze" to capture screenshots and interact by visual coordinates instead of DOM elements.`;
    }

    const prompt = PromptManager.getReasoningPrompt(contextString, lowDomWarningNotice);

    const responseText = await generateAiReply({
      prompt,
      history: [],
      pageContext
    });

    try {
      const parsed = robustJsonParse<Partial<ReasoningDecision>>(responseText);
      
      const reasoning = parsed.reasoning || "Reasoning trace not generated by LLM.";
      let selectedTool = (parsed.selectedTool || "chat_fallback") as ActionType;
      const confidence = typeof parsed.confidence === "number" ? parsed.confidence : 0.5;
      
      // Auto-fallback mapping on low DOM confidence
      if (domConfidence < DOM_CONFIDENCE_THRESHOLD) {
        if (selectedTool === "click_element") {
          selectedTool = "vision_click";
        } else if (selectedTool === "fill_input") {
          selectedTool = "vision_fill";
        } else if (selectedTool === "fill_form") {
          selectedTool = "vision_fill"; // Map visual forms to sequential inputs
        }
      }

      // Ensure status is valid
      let status: ReasoningDecision["status"] = "continue";
      if (parsed.status === "retry" || parsed.status === "replan" || parsed.status === "complete") {
        status = parsed.status;
      }

      return {
        reasoning,
        selectedTool,
        confidence,
        status
      };
    } catch (error) {
      console.error("Failed to parse reasoning decision JSON. Raw response:", responseText, error);
      return {
        reasoning: "Failed to parse structured reasoning decision, falling back to chat.",
        selectedTool: domConfidence < 0.50 ? "vision_analyze" : "chat_fallback",
        confidence: 0.2,
        status: "complete"
      };
    }
  }
};
