import { describe, expect, it, vi } from "vitest";

// Mock aiService generateAiReply
const mockGenerateAiReply = vi.fn();
vi.mock("./aiService", () => ({
  generateAiReply: (args: any) => mockGenerateAiReply(args)
}));

import { ReasoningEngine } from "./reasoningEngine";

describe("ReasoningEngine", () => {
  const mockPageContext = {
    title: "Job",
    url: "https://example.com",
    content: "a".repeat(400),
    host: "example.com",
    selectedText: "",
    description: ""
  };

  it("successfully parses a valid reasoning JSON decision", async () => {
    mockGenerateAiReply.mockResolvedValueOnce(
      JSON.stringify({
        reasoning: "Goal is to extract job, so we use extract_job tool.",
        selectedTool: "extract_job",
        confidence: 0.95,
        status: "continue"
      })
    );

    const result = await ReasoningEngine.reason("mock context", mockPageContext);
    expect(result).toEqual({
      reasoning: "Goal is to extract job, so we use extract_job tool.",
      selectedTool: "extract_job",
      confidence: 0.95,
      status: "continue"
    });
    expect(mockGenerateAiReply).toHaveBeenCalledWith({
      prompt: expect.stringContaining("mock context"),
      history: [],
      pageContext: mockPageContext
    });
  });

  it("handles missing optional or malformed fields and returns defaults", async () => {
    mockGenerateAiReply.mockResolvedValueOnce(
      JSON.stringify({
        // missing reasoning and confidence
        selectedTool: "fill_form",
        status: "invalid_status_here"
      })
    );

    const result = await ReasoningEngine.reason("mock context", mockPageContext);
    expect(result).toEqual({
      reasoning: "Reasoning trace not generated by LLM.",
      selectedTool: "fill_form",
      confidence: 0.5, // Default confidence
      status: "continue" // Default status when invalid
    });
  });

  it("recovers and returns fallback decision on invalid JSON output from LLM", async () => {
    mockGenerateAiReply.mockResolvedValueOnce(
      "This is not a JSON string, it's plain text."
    );

    const result = await ReasoningEngine.reason("mock context", mockPageContext);
    expect(result).toEqual({
      reasoning: "Failed to parse structured reasoning decision, falling back to chat.",
      selectedTool: "chat_fallback",
      confidence: 0.2,
      status: "complete"
    });
  });
});
